version: "3.9"

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: camila123
      MYSQL_USER: camila
      MYSQL_PASSWORD: camila123
      MYSQL_DATABASE: todolist
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/banco.sql:/docker-entrypoint-initdb.d/banco.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    ports:
      - "3333:3333"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: camila
      DB_PASSWORD: camila123
      DB_DATABASE: todolist

volumes:
  db_data: