apiVersion: apps/v1
kind: Deployment
metadata:
  name: provafinal-devops
  labels:
    app: provafinal-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provafinal-devops
  template:
    metadata:
      labels:
        app: provafinal-devops
    spec:
      containers:
        - name: provafinal-devops
          image: jkvuacamila/provafinal-devops:latest
          ports:
            - containerPort: 3333
          env:
            env:
            - name: DATABASE_HOST
              value: mysql-service
            - name: DATABASE_PORT
              value: "3306"