apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: prova-fastapi
  newName: jkvuacamila/provafinal-devops
  newTag: fb48ea612ec2bc3e1289d88d9c5ce861352018af
- name: provafinal-devops
  newName: jkvuacamila/provafinal-devops
  newTag: 2f703e434e3113f3fdde65011da0c767f25ada23
