apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: provafinal-devops
  newName: jkvuacamila/provafinal-devops
  newTag: 47d5262d262577beeef19892fd0a820079eb8d2d
