apiVersion: v1
kind: Service
metadata:
  name: provafinal-devops
spec:
  selector:
    app: provafinal-devops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3333
      nodePort: 30333
  type: NodePort
